export const AppIcons = {
  ico_arrow_down: require("./icons/ico_arrow_down.png"),
  ico_arrow_left: require("./icons/ico_arrow_left.png"),
  ico_arrow_right: require("./icons/ico_arrow_right.png"),
  ico_arrow_up: require("./icons/ico_arrow_up.png"),
  ico_home: require("./icons/ico_home.png"),
  ico_check: require("./icons/ico_check.png"),
  ico_check_circle_fill: require("./icons/ico_check_circle_fill.png"),
  ico_close: require("./icons/ico_close.png"),
  ico_warning_circle_fill: require("./icons/ico_warning_circle_fill.png"),
  ico_warning_triangle_fill: require("./icons/ico_warning_triangle_fill.png"),
  camera: require("./icons/camera.png"),
  vector: require("./icons/Vector.png"),
  image: require("./icons/image-01-filled.png"),
  camera_video: require("./icons/camera_video.png"),
  location: require("./icons/location.png"),
  user_add: require("./icons/user-add.png"),
  smile_ellipse: require("./icons/smile-ellipse.png"),
  smile: require("./icons/Input-Div.png"),
  dot: require("./icons/Label.png"),
  public: require("./icons/public.png"),
  edit: require("./icons/Frame8.png"),
};
